First part homework
eugeneshumilin/go-hardcode pull request #1
Opened 2020-10-13 19:37 UTC by eugeneshumilin

2020-10-14 05:42 UTC, DmitriyVTitov approved these changes

2020-10-14 05:42 UTC, DmitriyVTitov commented on hw1/cmd/fibonacci/main.go
> +		fmt.Println(f)
тогда уж не выводить f при наличии ошибки
но это так, придирка

2020-10-14 05:42 UTC, DmitriyVTitov commented on hw1/pkg/fibonacci/fibonacci.go
> +	if n > 20 || n == 0 || n < 0 {
n > 20 || n <= 0

2020-10-14 05:42 UTC, DmitriyVTitov commented on hw1/pkg/fibonacci/fibonacci.go
> +		return -1, errors.New("value cannot be greater than 20 and less than 0")
я считаю, что при наличии ошибки специальных значений типа -1 выдавать не надо
чище получается, если объявить переменную-результат и отдавать её (в данном случае будет 0, как значение по умолчанию)
если кто-то не проверяет ошибки - его проблема, к тому же -1 - валидное число Фибоначчи

2020-10-18 15:35 UTC, DmitriyVTitov requested changes
Алгоритм неверен. Ну и по мелочи, но это так, не существенно для первой работы.

2020-10-18 15:35 UTC, DmitriyVTitov commented on hw1/cmd/fibonacci/main.go
> +		fmt.Println(errors.New("value cannot be greater than 20"))
тут ошибка создаётся впустую. достаточно просто строки )

2020-10-18 15:35 UTC, DmitriyVTitov commented on hw1/cmd/fibonacci/main.go
> +	f, err := fibonacci.Fib(*n)
а какую ошибку может выдавать алгоритм в принципе? даже интересно.

2020-10-18 15:35 UTC, DmitriyVTitov commented on hw1/pkg/fibonacci/fibonacci.go
> +func Fib(n int) (int, error) {
а зачем тут ошибка вторым результатом? она же нигде не возникает ни при каком раскладе!

2020-10-18 15:35 UTC, DmitriyVTitov commented on hw1/pkg/fibonacci/fibonacci_test.go
> +}
я написал вот такой тест, попроще:

```
func TestFib(t *testing.T) {
	for i := 0; i <= 10; i++ {
		f, _ := Fib(i)
		t.Log(i, ":", f)
	}
}
```

Результат:

```
=== RUN   TestFib
    fibo_test.go:8: 0 : 1
    fibo_test.go:8: 1 : 0
    fibo_test.go:8: 2 : 1
    fibo_test.go:8: 3 : 1
    fibo_test.go:8: 4 : 2
    fibo_test.go:8: 5 : 3
    fibo_test.go:8: 6 : 5
    fibo_test.go:8: 7 : 8
    fibo_test.go:8: 8 : 13
    fibo_test.go:8: 9 : 21
    fibo_test.go:8: 10 : 34
```

Не сходится с Википедией :)

2020-10-18 17:13 UTC, eugeneshumilin commented on hw1/pkg/fibonacci/fibonacci_test.go
> +}
0 в кач-ве аргумента я не предусмотрел :) В последовательности Фибоначчи ведь нет 0-го элемента, сделаю какой-то явный возврат при аргументе 0, как и с > 20

2020-10-18 17:15 UTC, DmitriyVTitov commented on hw1/pkg/fibonacci/fibonacci_test.go
> +}
0 - 0
1 - 1
...
10 - 55

2020-10-18 17:22 UTC, eugeneshumilin commented on hw1/pkg/fibonacci/fibonacci_test.go
> +}
@DmitriyVTitov
Чи́сла Фибона́ччи (иногда пишут Фибона́чи[2]) — элементы числовой последовательности
0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 17711

0 это 1-е число Фибоначчи в моём алгоритме)
То есть, Fib(1) вернёт 0. Разве правильно вести индексацию последовательности чисел Фибоначчи с 0 как в массиве?)

2020-10-18 17:24 UTC, DmitriyVTitov commented on hw1/pkg/fibonacci/fibonacci_test.go
> +}
OK

2020-10-18 17:25 UTC, DmitriyVTitov approved these changes

2020-10-20 16:17 UTC, merged